# Generated by Django 5.0.6 on 2024-11-24 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0002_category_alter_task_is_used_in_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Theme')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='difficulty',
            field=models.IntegerField(null=True, verbose_name='User difficulty'),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.IntegerField(null=True, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='task',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ege.theme', verbose_name='Theme'),
        ),
    ]
