# Generated by Django 5.0.6 on 2024-12-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0002_category_alter_task_is_used_in_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='News` categories'),
        ),
    ]
