# Generated by Django 5.0.6 on 2025-02-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0004'),
        ('main_app', '0007_category_alter_news_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
