# Generated by Django 5.0.6 on 2024-12-22 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0004'),
        ('main_app', '0002_news_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rates', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='ege.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='news',
            name='rate',
            field=models.ManyToManyField(to='main_app.rate'),
        ),
    ]
