# Generated by Django 5.0.6 on 2024-11-24 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0003_theme_task_difficulty_task_type_task_theme'),
        ('main_app', '0002_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='ege.category', verbose_name='Category'),
        ),
    ]
