# Generated by Django 5.0.6 on 2024-12-22 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rate_alter_news_category_news_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.rate'),
        ),
    ]
