# Generated by Django 5.0.6 on 2024-12-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_news_rate_news_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='rates',
        ),
        migrations.AddField(
            model_name='rate',
            name='rate',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], null=True, verbose_name='User rate'),
        ),
        migrations.RemoveField(
            model_name='news',
            name='rate',
        ),
        migrations.AddField(
            model_name='news',
            name='rate',
            field=models.ManyToManyField(to='main_app.rate'),
        ),
    ]
