# Generated by Django 5.0.6 on 2025-01-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_rate_rates_rate_rate_remove_news_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='avg_rate',
            field=models.FloatField(null=True, verbose_name='Average rate'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], null=True, verbose_name='User rate'),
        ),
    ]
